name: Build and Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Check if Docker is available
      run: docker --version

    - name: Check if Python is available
      run: python --version

    - name: Check if Pip is available
      run: pip --version

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: karpik3004/devops-mini-app:latest
        build-args: |
          BUILD_VERSION=latest

    # Uruchomienie testów
    - name: Run tests
      run: |
        docker run --rm -v $(pwd):/app -w /app python:3.10-slim bash -c "pip install -r requirements.txt && pytest"